
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ba_server_development

test:
  <<: *default
  database: ba_server_test

production:
  <<: *default
  database: ba_server_production
  username: ba_server
  password: <%= ENV['BA_SERVER_DATABASE_PASSWORD'] %>
