require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'lib/ba/ba_commands/usage_stats_command.rb'
    - 'lib/ba/ba_commands/help_command.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/ba/ba_commands/usage_stats_command.rb'
    - 'lib/ba/ba_commands/help_command.rb'
    - 'lib/ba/models/emoji.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/ba/ba_commands/usage_stats_command.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'lib/ba/ba_commands/help_command.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/ba/models/emoji_spec.rb'
