require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'lib/ba/utils/embeds.rb'

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Enabled: false
