default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres_user
  password: postgres_pass

development:
  <<: *default
  database: ba_development
  host: localhost
  port: 5432
test:
  <<: *default
  database: ba_test
  host: localhost
  port: 5432
production:
  <<: *default
  database: ba_production
  username: ba_database_user
  password: <%= ENV['BA_DATABASE_PASSWORD'] %>
