name: Bot Build

on: [push, pull_request]

jobs:
  build:
    env:
      TOKEN: 'completely real token'
      DATABASE_URL: 'postgres://postgres_user:postgres_pass@localhost/ba_development?pool=5'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install dependencies
      run: |
        sudo apt-get install libpq-dev
        gem install bundler
        cd bot
        bundle install --jobs 4 --retry 3
    - name: Lint
      run: |
        cd bot
        bundle exec rubocop
    - name: Test Bot
      run: |
        cd bot
        bundle exec rspec
